### ISSUE TITLE
Instructions Need updating

### ISSUE THREAD

**Issue by Eatitup86** [Albeoris/Memoria.FF1#2]
Just providing these in case you want to use them. I posted this on a FF Modding Discord that has been collaborating a lot with the new pixel remasters. Will need updated just a bit if you resolve that Export always on issue. :)

1 - Download BepInEx Loader + Mod v2021.08.02 from: https://github.com/Albeoris/Memoria.FF1
2 - Extract to the root of your game install.
3 - Run your game + close it.
4 - Navigate to InstallDir\BepInEx\config and open Memoria.ff1.cfg
5 - Set ExportEnabled = true
6 - Run your game again, wait a bit for extraction to complete then close it.
7 - Navigate to: InstallDir\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data to explore the files within and make any modifications you would like to try.
8 - Launch the game again and the changes will be applied automatically.

**Comment by Albeoris** [comment]
Just update the README. Thank you.
